dist: trusty

language: ruby
cache: bundler
rvm:
  # - "2.1"
  # - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"

before_install:
  - gem install bundler

script:
  - bundle exec rspec
  # - bundle exec bin/rubocop

bundler_args: --without development

matrix:
  include:
    - rvm: jruby-20mode # JRuby in 1.9 mode
      dist: precise
